name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: print job details
        run: |
          echo "github_ref ${{ github.ref }}"
          echo "github_event_name ${{ github.event_name }}"

      - name: set up
        run: npm ci

      - name: test
        run: npm run test
